# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: objective-c
before_install:
  - bundle update
script:
  - bundle exec fastlane test

