
fastlane_version "2.62.0"

default_platform :ios

platform :ios do

  team_id = "1042045"

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Increments the build number"
  lane :build_number do
    version = get_version_number
    build_number = get_build_number
    build_number = latest_testflight_build_number(version: version, initial_build_number: build_number, team_id: team_id) + 1
    increment_build_number(build_number: build_number)
    commit_version_bump(message: "[ci skip] Incremented build number to #{build_number}")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Scroggle") # Build your app - more options available
    pilot(team_id: team_id, skip_waiting_for_build_processing: true)

  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Scroggle") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

end
