
fastlane_version "2.62.0"

default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Increments the build number"
  lane :build_number do
    build_number = get_build_number
    build_number = latest_testflight_build_number(initial_build_number: build_number, team_id: 1042045) + 1
    increment_build_number(build_number: build_number)
    commit_version_bump(message: "[ci skip] Incremented build number to #{build_number}")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Scroggle") # Build your app - more options available
    pilot

  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Scroggle") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

end
